openrem/openrem/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^openrem/', include('remapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # Login / logout.
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'remapp.views.logout_page'),

)

openrem/remapp/urls.py
#    OpenREM - Radiation Exposure Monitoring tools for the physicist
#    Copyright (C) 2012,2013  The Royal Marsden NHS Foundation Trust
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    Additional permission under section 7 of GPLv3:
#    You shall not make any use of the name of The Royal Marsden NHS
#    Foundation trust in connection with this Program in any press or 
#    other public announcement without the prior written consent of 
#    The Royal Marsden NHS Foundation Trust.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
..  module:: urls.
    :synopsis: Module to match URLs and pass over to views or export modules.

..  moduleauthor:: Ed McDonagh

"""

from django.conf.urls import patterns, include, url
from django_filters.views import FilterView
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from remapp.models import Accumulated_projection_xray_dose, General_study_module_attributes


urlpatterns = patterns('remapp.views',

    url(r'^$',
        'openrem_home'),

    url(r'^rf/$',
        'rf_summary_list_filter'),
    url(r'^rf/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=General_study_module_attributes,
            template_name='remapp/rfdetail.html'))),

    url(r'^ct/$',
        'ct_summary_list_filter'),
    url(r'^ct/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=General_study_module_attributes,
            template_name='remapp/ctdetail.html'))),

    url(r'^mg/$',
        'mg_summary_list_filter'),
    url(r'^mg/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=General_study_module_attributes,
            template_name='remapp/mgdetail.html'))),

)

urlpatterns += patterns('remapp.exports.exportcsv',
    url(r'^export/openrem/rf/',
        'exportFL2excel'),

    url(r'^export/openrem/ct/',
        'exportCT2excel'),

    url(r'^export/openrem/mg/',
        'exportMG2excel'),
)

urlpatterns += patterns('remapp.exports',
    url(r'^xlsx/openrem/ct/',
        'xlsx.ctxlsx'),
)

openrem/remapp/models.py
#    OpenREM - Radiation Exposure Monitoring tools for the physicist
#    Copyright (C) 2012,2013  The Royal Marsden NHS Foundation Trust
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    Additional permission under section 7 of GPLv3:
#    You shall not make any use of the name of The Royal Marsden NHS
#    Foundation trust in connection with this Program in any press or 
#    other public announcement without the prior written consent of 
#    The Royal Marsden NHS Foundation Trust.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
..  module:: models.
    :synopsis: Models to create the database tables and relationships.

..  moduleauthor:: Ed McDonagh

"""

# Following two lines added so that sphinx autodocumentation works. 
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'openrem.settings'
from django.db import models

class Content_item_descriptions(models.Model):
    """Table to hold all the context ID code values and code meanings.
    
    + Should be renamed Context_identifiers. If it does, I think it would only need to be edited in tools.get_values.get_or_set_cid and admin, then a South migration.
    + Could be prefilled from the tables in DICOM 3.16, but is actually populated as the codes occur. This assumes they are used correctly.
    
    """    
    code_value = models.CharField(max_length=16)
    code_meaning = models.CharField(max_length=64,blank=True)
    cid_table = models.CharField(max_length=16,blank=True)
    def __unicode__(self):
        return self.code_meaning
    class Meta:
        ordering = ['code_value']

class General_study_module_attributes(models.Model): # C.7.2.1
    """General Study Module C.7.2.1
    
    Specifies the Attributes that describe and identify the Study 
    performed upon the Patient.
    
    From DICOM Part 3: Information Object Definitions Table C.7-3

    Additional to the module definition:
        * performing_physician_name
        * operator_name
        * modality_type
        * procedure_code_value_and_meaning
        * requested_procedure_code_value_and_meaning
    """
    study_instance_uid = models.CharField(max_length=64,blank=True)
    study_date = models.DateField(blank=True, null=True)
    study_time = models.TimeField(blank=True, null=True)
    referring_physician_name = models.CharField(max_length=64,blank=True, null=True)
    referring_physician_identification = models.CharField(max_length=64,blank=True, null=True)
    study_id = models.CharField(max_length=16,blank=True,null=True)
    accession_number = models.CharField(max_length=16,blank=True,null=True)
    study_description = models.CharField(max_length=64,blank=True,null=True)
    physician_of_record = models.CharField(max_length=64,blank=True,null=True)
    name_of_physician_reading_study = models.CharField(max_length=64,blank=True,null=True)
    # Possibly need a few sequences linked to this table...
    # Next three don't belong in this table, but they don't belong anywhere in a RDSR!
    performing_physician_name = models.CharField(max_length=64,blank=True,null=True)
    operator_name = models.CharField(max_length=64,blank=True,null=True)
    modality_type = models.CharField(max_length=8,blank=True,null=True)
    procedure_code_value = models.CharField(max_length=16,blank=True,null=True)
    procedure_code_meaning = models.CharField(max_length=64,blank=True,null=True)
    requested_procedure_code_value = models.CharField(max_length=16,blank=True,null=True)
    requested_procedure_code_meaning = models.CharField(max_length=64,blank=True,null=True)
    def __unicode__(self):
        return self.study_instance_uid

class Projection_xray_radiation_dose(models.Model): # TID 10001
    """Projection X-Ray Radiation Dose template TID 10001
    
    From DICOM Part 16:
        This template defines a container (the root) with subsidiary content items, each of which represents a
        single projection X-Ray irradiation event entry or plane-specific dose accumulations. There is a defined
        recording observer (the system or person responsible for recording the log, generally the system). A
        Biplane irradiation event will be recorded as two individual events, one for each plane. Accumulated
        values will be kept separate for each plane.
    
    """
    general_study_module_attributes = models.ForeignKey(General_study_module_attributes)
    procedure_reported = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_procedure')
    has_intent = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_intent')
    acquisition_device_type = models.CharField(max_length=16,blank=True)
    scope_of_accumulation = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_scope')
    xray_detector_data_available = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_detector')
    xray_source_data_available = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_source')
    xray_mechanical_data_available = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_mech')
    comment = models.TextField(max_length=512,blank=True)
    source_of_dose_information = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10001_infosource') # might need to be a table on its own as is 1-n, even though it should only list the primary source...

class Accumulated_xray_dose(models.Model): # TID 10002
    """Accumulated X-Ray Dose TID 10002
    
    From DICOM Part 16:
        This general template provides detailed information on projection X-Ray dose value accumulations over
        several irradiation events from the same equipment (typically a study or a performed procedure step).
    
    """
    projection_xray_radiation_dose = models.ForeignKey(Projection_xray_radiation_dose)
    acquisition_plane = models.ForeignKey(Content_item_descriptions,blank=True,null=True)

class Calibration(models.Model):
    """Table to hold the calibration information
    
    + Container in TID 10002 Accumulated X-ray dose
    
    """
    accumulated_xray_dose = models.ForeignKey(Accumulated_xray_dose)
    dose_measurement_device = models.ForeignKey(Content_item_descriptions,blank=True,null=True)
    calibration_date = models.DateTimeField(blank=True, null=True)
    calibration_factor = models.DecimalField(max_digits=8,decimal_places=5,blank=True,null=True)
    calibration_uncertainty = models.DecimalField(max_digits=8,decimal_places=5,blank=True,null=True)
    calibration_responsible_party = models.CharField(max_length=64,blank=True)

class Irradiation_event_xray_data(models.Model): # TID 10003
    """Irradiation Event X-Ray Data TID 10003
    
    From DICOM part 16:
        This template conveys the dose and equipment parameters of a single irradiation event.
    
    """
    projection_xray_radiation_dose = models.ForeignKey(Projection_xray_radiation_dose)
    acquisition_plane = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_plane')
    irradiation_event_uid = models.CharField(max_length=64,blank=True)
    irradiation_event_label = models.CharField(max_length=64,blank=True)
    label_type = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_labeltype')
    date_time_started = models.DateTimeField(blank=True, null=True)
    irradiation_event_type = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_eventtype')
    acquisition_protocol = models.CharField(max_length=64,blank=True)
    anatomical_structure = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_anatomy')
    laterality = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_laterality')
    image_view = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_view')
    projection_eponymous_name = models.CharField(max_length=16,blank=True)
    patient_table_relationship = models.CharField(max_length=16,blank=True)
    patient_orientation = models.CharField(max_length=16,blank=True)
    patient_orientation_modifier = models.CharField(max_length=16,blank=True)
    target_region = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_region')
    dose_area_product = models.DecimalField(max_digits=16,decimal_places=12,blank=True,null=True)
    half_value_layer = models.DecimalField(max_digits=8,decimal_places=5,blank=True,null=True)
    entrance_exposure_at_rp = models.DecimalField(max_digits=8,decimal_places=4,blank=True,null=True)
    reference_point_definition = models.ForeignKey(Content_item_descriptions,blank=True,null=True, related_name='tid10003_rpdefinition')
    breast_composition = models.CharField(max_length=16,blank=True) # TID 4007, CID 6000
    percent_fibroglandular_tissue = models.DecimalField(max_digits=6,decimal_places=3,blank=True,null=True) # TID 4007
    comment = models.TextField(max_length=512,blank=True)
    def __unicode__(self):
        return self.irradiation_event_uid
    def convert_gym2_to_cgycm2(self): # not used anywhere?
        return 1000000*self.dose_area_product

    
class Image_view_modifier(models.Model): # EV 111032

openrem/remapp/templates/remapp/base.html
{% extends "base.html" %}

openrem/remapp/templates/remapp/filteredbase.html
{% extends "remapp/base.html" %}


    {% block headextras %}
    <!-- Bootstrap-datepicker CSS -->
    <!-- Bootstrap-datepicker JavaScript
    ================================================== -->
     <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/datepicker3.css">
    
    <script src="{{ STATIC_URL }}js/jquery-1.11.0.min.js"></script>
  
     <script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
    {% block headscript %}
    {% endblock %}
    {% endblock %}


      {% block mainblock %}
      <div class="row">
        <div class="col-md-9">
          {% block col1 %}
          {% endblock %}
        </div>
        <div class="col-md-3">
          {% block col2 %}
          {% endblock %}
        </div>
      </div>
      {% endblock %}


    {% block jsblock %}
    {% endblock %}

openrem/remapp/templates/remapp/mgdetail.html
{% extends "remapp/base.html" %}

{% block navbar %}
            <li><a href="/openrem/ct">CT</a></li>
            <li><a href="/openrem/rf">Fluoroscopy</a></li>
            <li class="active"><a href="/openrem/mg">Mammography</a></li>
{% endblock %}


{% block mainblock %}		
<h1>Detail list of events</h1>

<ul>
    <li>Accession number: {{ general_study_module_attributes.accession_number }}</li>
    <li>Study date: {{ general_study_module_attributes.study_date }}</li>
    <li>Study time: {{ general_study_module_attributes.study_time }}</li>
    <li>Study description: {{ general_study_module_attributes.study_description }}</li>
    <li>Requested procedure: {{ general_study_module_attributes.requested_procedure_code_meaning }}</li>
    <li>Patient age: {{ general_study_module_attributes.patient_study_module_attributes_set.get.patient_age_decimal|floatformat:1 }}</li>
    <li>Hospital: {{ general_study_module_attributes.general_equipment_module_attributes_set.get.institution_name }}</li>
    <li>
        Scanner: 
        {{ general_study_module_attributes.general_equipment_module_attributes_set.get.manufacturer }} |
        {{ general_study_module_attributes.general_equipment_module_attributes_set.get.manufacturer_model_name }} |
        {{ general_study_module_attributes.general_equipment_module_attributes_set.get.station_name }}        
    </li>
    <li>Study UID: {{ general_study_module_attributes.study_instance_uid }}</li>
    <li>Test patient indicators? {{ general_study_module_attributes.patient_module_attributes_set.get.not_patient_indicator }}</li>
</ul>

<table class="table table-striped table-bordered">
    <th>Time</th>
    <th>Acquisition protocol</th>
    <th>View</th>
    <th>Compression thickness</th>
    <th>Target</th>
    <th>Filter</th>
    <th>kVp</th>
    <th>mA</th>
    <th>Exposure time</th>
    <th>ESD</th>
    <th>AGD (mGy)</th>
    {% for event in general_study_module_attributes.projection_xray_radiation_dose_set.get.irradiation_event_xray_data_set.all %}
    <tr>
        <td>{{ event.date_time_started|time:"H:i.s" }}</td>
        <td>{{ event.acquisition_protocol }}</td>
        <td>{{ event.image_view }}</td>
        <td>{{ event.irradiation_event_xray_mechanical_data_set.get.compression_thickness|floatformat:0  }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.anode_target_material }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.xray_filters_set.get.xray_filter_material }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.kvp_set.get.kvp|floatformat:0 }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.average_xray_tube_current|floatformat:0 }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.exposure_time|floatformat:0 }}</td>
        <td>{{ event.entrance_exposure_at_rp }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.average_glandular_dose }}</td>
    </tr>
    <tr>
        <td colspan = "11"><small> <strong>Exposure Control Mode Description:</strong>{{ event.comment }} </small></td>
    </tr>
    {% endfor %}
</table>



{% endblock %}	

openrem/remapp/templates/remapp/mgfiltered.html
{% extends "remapp/filteredbase.html" %}

{% block navbar %}
            <li><a href="/openrem/ct">CT</a></li>
            <li><a href="/openrem/rf">Fluoroscopy</a></li>
            <li class="active"><a href="/openrem/mg">Mammography</a></li>
{% endblock %}

{% block toprow %}
      {% load pagination_tags %}    
      <p>
        There are {{ filter.count }} studies in this list.
      </p>
        {% if admin.exportperm or admin.adminperm %}
        <ul>
          <li><strong>Note:</strong> Apply the filter first to refine what is exported.</li>
          <li><a href="/openrem/export{{ request.get_full_path }}">Export to CSV</a> </li>
        </ul>
        {% else %}
        <p>
          Sorry, you don't have enough permissions to enable study export.
        </p>
        {% endif %}
{% endblock %}



{% block col2 %}


    {{ studyfilter }}

          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Exam filter</h3>
            </div>
            <div class="panel-body">
                <i>Date format yyyy-mm-dd</i>
                <form action="" method="get" class="form-horizontal role="form">
                        {% for field in filter.form %}
                            <div class="form-group">
                                <div class="col-xs-4">
                                    <label>{{ field.label_tag }}</label>
                                </div>
                                <div class="col-xs-8">
                                  {{ field.errors }}
                                  {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                    </table>
                    <input type="submit" />
                </form> 
            </div>
          </div>
    
<script>
$('.datepicker').datepicker({
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true
    });
</script>

{% endblock %}

{% block col1 %}

    {% autopaginate filter.qs 50 as filter_list %}
    {% paginate %}

    <table class="table table-striped">
        <th>Institution</th><th>Make | Model | Station name</th><th>Date</th><th>Protocol | Accession number</th><th>Number of events</th><th>Laterality</th><th>Accumulated AGD (mGy)</th>
        {% if admin.adminperm %}
        <th>Delete?</th>
        {% endif %}
        {% for exam in filter_list %}
        <tr>
            <td>{{ exam.general_equipment_module_attributes_set.get.institution_name }}</td>
            <td>
                {{ exam.general_equipment_module_attributes_set.get.manufacturer }} | 
                {{ exam.general_equipment_module_attributes_set.get.manufacturer_model_name }} |
                {{ exam.general_equipment_module_attributes_set.get.station_name }}
            </td>
            <td>{{ exam.study_date|date:"Y-m-d" }} {{ exam.study_time|date:"H:i" }}</td>
            <td>
                <a href="/openrem/mg/{{ exam.id }}/">{{ exam.procedure_code_meaning }}</a> |
                {{ exam.accession_number }}
            </td>
            <td>{{ exam.projection_xray_radiation_dose_set.get.irradiation_event_xray_data_set.count }}</td>
            <td>{{ exam.projection_xray_radiation_dose_set.get.accumulated_xray_dose_set.get.accumulated_mammography_xray_dose_set.get.laterality }}</td>
            <td>{{ exam.projection_xray_radiation_dose_set.get.accumulated_xray_dose_set.get.accumulated_mammography_xray_dose_set.get.accumulated_average_glandular_dose }}</td>
            {% if admin.adminperm %}
            <td>Delete</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>

    {% paginate %}

 
{% endblock %}

openrem/remapp/templates/remapp/rfdetail.html
{% extends "remapp/base.html" %}

{% block navbar %}
            <li><a href="/openrem/ct">CT</a></li>
            <li class="active"><a href="/openrem/rf">Fluoroscopy</a></li>
            <li><a href="/openrem/mg">Mammography</a></li>
{% endblock %}

{% block mainblock %}		
<h1>Detail list of events</h1>

<ul>
    <li>Accession number: {{ general_study_module_attributes.accession_number }}</li>
    <li>Study date: {{ general_study_module_attributes.study_date }}</li>
    <li>Study time: {{ general_study_module_attributes.study_time }}</li>
    <li>Study description: {{ general_study_module_attributes.study_description }}</li>
    <li>Requested procedure: {{ general_study_module_attributes.requested_procedure_code_meaning }}</li>
    <li>Patient age: {{ general_study_module_attributes.patient_study_module_attributes_set.get.patient_age_decimal|floatformat:1 }}</li>
    <li>Patient weight: {{ general_study_module_attributes.patient_study_module_attributes_set.get.patient_weight|floatformat:1 }} kg</li>
    <li>Total DAP: {{ general_study_module_attributes.projection_xray_radiation_dose_set.get.accumulated_xray_dose_set.get.accumulated_projection_xray_dose_set.get.convert_gym2_to_cgycm2|floatformat:1 }} cGy.cm2</li>
    <li>Total dose at RP: {{ general_study_module_attributes.projection_xray_radiation_dose_set.get.accumulated_xray_dose_set.get.accumulated_projection_xray_dose_set.get.dose_rp_total|floatformat:6 }} Gy</li>
    <li>Hospital: {{ general_study_module_attributes.general_equipment_module_attributes_set.get.institution_name }}</li>
    <li>
        Scanner: 
        {{ general_study_module_attributes.general_equipment_module_attributes_set.get.manufacturer }} |
        {{ general_study_module_attributes.general_equipment_module_attributes_set.get.manufacturer_model_name }} |
        {{ general_study_module_attributes.general_equipment_module_attributes_set.get.station_name }}        
    </li>
    <li>Study UID: {{ general_study_module_attributes.study_instance_uid }}</li>
    <li>Test patient indicators? {{ general_study_module_attributes.patient_module_attributes_set.get.not_patient_indicator }}</li>
</ul>


<table class="table table-striped table-bordered">
    <th>Time</th><th>Acquisition protocol</th><th>DAP cGy.cm2</th><th>Exposure time</th><th>kVp</th><th>mA</th><th>Angle</th><th>II Diameter</th>
    {% for event in general_study_module_attributes.projection_xray_radiation_dose_set.get.irradiation_event_xray_data_set.all %}
    <tr>
        <td>{{ event.date_time_started|time:"H:i.s" }}</td>
        <td>{{ event.acquisition_protocol }}</td>
        <td>{{ event.convert_gym2_to_cgycm2|floatformat:3 }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.exposure_time }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.kvp_set.get.kvp }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.xray_tube_current_set.get.xray_tube_current }}</td>
        <td>{{ event.irradiation_event_xray_mechanical_data_set.get.positioner_primary_angle }}</td>
        <td>{{ event.irradiation_event_xray_source_data_set.get.ii_field_size }}</td>
    </tr>
    {% endfor %}
</table>

<a href="../list">Back to list</a>

{% if is_paginated %}
<p class="pagination">
    {% if has_next %}
    <a class="older" href="?page={{ next }}" title="View older posts">Older</a>
    {% endif %}
    {% if has_next and has_previous %} | {% endif %}
    {% if has_previous %}
    <a class="newer" href="?page={{ previous }}" title="View newer posts">Newer</a>
    {% endif %}
</p>
{% endif %}

{% endblock %}	

openrem/remapp/templates/remapp/rffiltered.html
{% extends "remapp/filteredbase.html" %}

{% block navbar %}
            <li><a href="/openrem/ct">CT</a></li>
            <li class="active"><a href="/openrem/rf">Fluoroscopy</a></li>
            <li><a href="/openrem/mg">Mammography</a></li>
{% endblock %}

{% block toprow %}
{% load pagination_tags %}    
      <p>
        There are {{ filter.count }} studies in this list.
      </p>
        {% if admin.exportperm or admin.adminperm %}
        <ul>
          <li><strong>Note:</strong> Apply the filter first to refine what is exported.</li>
          <li><a href="/openrem/export{{ request.get_full_path }}">Export to CSV</a> </li>
        </ul>
        {% else %}
        <p>
          Sorry, you don't have enough permissions to enable study export.
        </p>
        {% endif %}
{% endblock %}



{% block col2 %}


    {{ studyfilter }}

          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Exam filter</h3>
            </div>
            <div class="panel-body">
                <i>Date format yyyy-mm-dd</i>
                <form action="" method="get" class="form-horizontal role="form">
                        {% for field in filter.form %}
                            <div class="form-group">
                                <div class="col-xs-4">
                                    <label>{{ field.label_tag }}</label>
                                </div>
                                <div class="col-xs-8">
                                  {{ field.errors }}
                                  {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                    </table>
                    <input type="submit" />
                </form> 
            </div>
          </div>
          
<script>
$('.datepicker').datepicker({
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true
    });
</script>

    
{% endblock %}

{% block col1 %}

    {% autopaginate filter.qs 20 as filter_list %}
    {% paginate %}

    <table class="table table-striped">
        <th>Institution</th><th>Unit</th><th>Date</th><th>Study description | Accession number</th><th>Number of events</th><th>DAP Total cGy.cm2</th><th>Dose at RP total Gy</th><th>Physician</th>
        {% if admin.adminperm %}
        <th>Delete?</th>
        {% endif %}
        {% for exam in filter_list %}
        <tr>
            <td>{{ exam.general_equipment_module_attributes_set.get.institution_name }}</td>
            <td>
                {{ exam.general_equipment_module_attributes_set.get.manufacturer }} |
                {{ exam.general_equipment_module_attributes_set.get.manufacturer_model_name }} |
                {{ exam.general_equipment_module_attributes_set.get.station_name }}        
            </td>
            <td>{{ exam.study_date|date:"Y-m-d" }} {{ exam.study_time|date:"H:i" }}</td>
            <td>
                <a href="/openrem/rf/{{ exam.id }}/">{{ exam.study_description }}</a> |
                {{ exam.accession_number }}
            </td>
            <td>{{ exam.projection_xray_radiation_dose_set.get.irradiation_event_xray_data_set.count }}</td>
            <td>{{ exam.projection_xray_radiation_dose_set.get.accumulated_xray_dose_set.get.accumulated_projection_xray_dose_set.get.convert_gym2_to_cgycm2|floatformat:1 }}</td>
            <td>{{ exam.projection_xray_radiation_dose_set.get.accumulated_xray_dose_set.get.accumulated_projection_xray_dose_set.get.dose_rp_total|floatformat:6 }}</td>
            <td>{{ exam.performing_physician_name }}</td>
            {% if admin.adminperm %}
            <td>Delete</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>

    {% paginate %}

 
{% endblock %}